### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by anselanza** [nunofgs/pm2-datadog#4]
When I run `sudo pm2 install uphold/pm2-datadog` I always get the error:

> Error while executing:
> npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/uphold/pm2-datadog.git
> npm ERR!
> npm ERR! ERROR: Repository not found.
> npm ERR! fatal: Could not read from remote repository.
> npm ERR!
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> npm ERR!
> npm ERR! exited with error code: 128

Seems like git is trying to clone via SSH (why?).

**Comment by anselanza** [comment]
And trying to install from the correct (?) URL directly:

```
sudo pm2 install https://github.com/nunofgs/pm2-datadog               stephen@Stephens-MacBook-Pro
[PM2][Module] Installing module https://github.com/nunofgs/pm2-datadog
[PM2][Module] Calling [NPM] to install https://github.com/nunofgs/pm2-datadog ...
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/nunofgs/pm2-datadog.git /Users/stephen/.npm/_cacache/tmp/git-clone-8d55cfc7
npm ERR! /Users/stephen/.npm/_cacache/tmp/git-clone-8d55cfc7/.git: Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stephen/.npm/_logs/2017-11-21T11_30_25_168Z-debug.log
[PM2][ERROR] Installation failed
```

**Comment by anselanza** [comment]
Hmm seems like something specific to my environment on Mac OS. Installation on Windows host working just fine.

**Comment by nunofgs** [comment]
Hi @anselanza. A simple `pm2 install pm2-datadog` should suffice since the package is now in npm (I have to update the reader)

I’m using this on a Mac as well with no issues. Please reopen if the issue persists.

**Comment by anselanza** [comment]
Thanks for the feedback.

I ran a `npm cache clean --force` and tried installing again, and now it worked just fine! Must have been something weird with my setup.
